![title](Header__0007_3.png "Header")
___
# Chapter 3 - Basic Math and Statistics
## Segment 1 - Using NumPy to perform arithmetic operations on data

In [1]:
import numpy as np
from numpy.random import randn

In [2]:
np.set_printoptions(precision=2)

## Creating arrays
### Creating arrays using a list

In [3]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [4]:
b = np.array([[10,20,30], [40,50,60]])
b

array([[10, 20, 30],
       [40, 50, 60]])

### Creating arrays via assignment

In [5]:
np.random.seed(25)
c = 36*np.random.randn(6)
c

array([  8.22,  36.97, -30.23, -21.28, -34.45,  -8.  ])

In [6]:
d = np.arange(1,35)
d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

## Performing arthimetic on arrays

In [7]:
a * 10

array([10, 20, 30, 40, 50, 60])

In [8]:
c + a

array([  9.22,  38.97, -27.23, -17.28, -29.45,  -2.  ])

In [9]:
c - a

array([  7.22,  34.97, -33.23, -25.28, -39.45, -14.  ])

In [10]:
c * a

array([   8.22,   73.94,  -90.68,  -85.13, -172.24,  -48.02])

In [11]:
c / a

array([  8.22,  18.48, -10.08,  -5.32,  -6.89,  -1.33])

### Multiplying matrices and basic linear algebra

In [12]:
aa = np.array([[2.,4.,6.], [1.,3.,5.], [10.,20.,30.]])
aa

array([[  2.,   4.,   6.],
       [  1.,   3.,   5.],
       [ 10.,  20.,  30.]])

In [13]:
bb = np.array([[0.,1.,2.], [3.,4.,5.], [6.,7.,8.]])
bb

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.]])

In [14]:
aa*bb

array([[   0.,    4.,   12.],
       [   3.,   12.,   25.],
       [  60.,  140.,  240.]])

In [16]:
np.dot(aa,bb)

array([[  48.,   60.,   72.],
       [  39.,   48.,   57.],
       [ 240.,  300.,  360.]])