In [6]:
from sklearn import datasets
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
plt.style.use('ggplot')

In [7]:
iris=datasets.load_iris()

In [8]:
iris['data']

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2],
       [ 5.4,  3.9,  1.7,  0.4],
       [ 4.6,  3.4,  1.4,  0.3],
       [ 5. ,  3.4,  1.5,  0.2],
       [ 4.4,  2.9,  1.4,  0.2],
       [ 4.9,  3.1,  1.5,  0.1],
       [ 5.4,  3.7,  1.5,  0.2],
       [ 4.8,  3.4,  1.6,  0.2],
       [ 4.8,  3. ,  1.4,  0.1],
       [ 4.3,  3. ,  1.1,  0.1],
       [ 5.8,  4. ,  1.2,  0.2],
       [ 5.7,  4.4,  1.5,  0.4],
       [ 5.4,  3.9,  1.3,  0.4],
       [ 5.1,  3.5,  1.4,  0.3],
       [ 5.7,  3.8,  1.7,  0.3],
       [ 5.1,  3.8,  1.5,  0.3],
       [ 5.4,  3.4,  1.7,  0.2],
       [ 5.1,  3.7,  1.5,  0.4],
       [ 4.6,  3.6,  1. ,  0.2],
       [ 5.1,  3.3,  1.7,  0.5],
       [ 4.8,  3.4,  1.9,  0.2],
       [ 5. ,  3. ,  1.6,  0.2],
       [ 5. ,  3.4,  1.6,  0.4],
       [ 5.2,  3.5,  1.5,  0.2],
       [ 5.2,  3.4,  1.4,  0.2],
       [ 4.7,  3.2,  1.6,  0.2],
       [ 4

In [9]:
iris['target']

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [10]:
type(iris)

sklearn.datasets.base.Bunch

In [11]:
print(iris.keys())

['target_names', 'data', 'target', 'DESCR', 'feature_names']


In [12]:
iris.data.shape

(150, 4)

In [13]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'],
      dtype='|S10')

In [14]:
from sklearn.neighbors import KNeighborsClassifier

In [15]:
knn=KNeighborsClassifier()

In [16]:
knn.fit(iris['data'],iris['target'])

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
X=iris['data']

In [19]:
y=iris['target']

In [20]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=21)

In [21]:
X_train

array([[ 5.5,  3.5,  1.3,  0.2],
       [ 4.9,  3.1,  1.5,  0.1],
       [ 4.3,  3. ,  1.1,  0.1],
       [ 6.2,  2.2,  4.5,  1.5],
       [ 4.8,  3.4,  1.6,  0.2],
       [ 6.9,  3.1,  4.9,  1.5],
       [ 5. ,  3.3,  1.4,  0.2],
       [ 6.7,  3.1,  4.4,  1.4],
       [ 7.7,  2.6,  6.9,  2.3],
       [ 5.7,  2.8,  4.5,  1.3],
       [ 5.8,  2.7,  4.1,  1. ],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5.1,  3.5,  1.4,  0.3],
       [ 7.7,  3. ,  6.1,  2.3],
       [ 4.7,  3.2,  1.6,  0.2],
       [ 5.4,  3.7,  1.5,  0.2],
       [ 4.6,  3.6,  1. ,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 5.4,  3.4,  1.5,  0.4],
       [ 5.7,  2.9,  4.2,  1.3],
       [ 5.5,  2.5,  4. ,  1.3],
       [ 5.2,  3.5,  1.5,  0.2],
       [ 6.7,  2.5,  5.8,  1.8],
       [ 6.4,  3.2,  4.5,  1.5],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 5.4,  3.9,  1.3,  0.4],
       [ 4.9,  2.5,  4.5,  1.7],
       [ 6.7,  3.1,  4.7,  1.5],
       [ 4.9,  3.1,  1.5,  0.1],
       [ 6.5,  3. ,  5.8,  2.2],
       [ 5

In [22]:
X_test

array([[ 5.8,  2.6,  4. ,  1.2],
       [ 5.1,  3.8,  1.9,  0.4],
       [ 5. ,  3.4,  1.5,  0.2],
       [ 5.1,  3.7,  1.5,  0.4],
       [ 5.7,  3. ,  4.2,  1.2],
       [ 6.6,  3. ,  4.4,  1.4],
       [ 5.4,  3.4,  1.7,  0.2],
       [ 5.6,  2.8,  4.9,  2. ],
       [ 5. ,  3.4,  1.6,  0.4],
       [ 5.1,  3.8,  1.5,  0.3],
       [ 5.5,  2.4,  3.7,  1. ],
       [ 5.6,  3. ,  4.1,  1.3],
       [ 6.8,  3.2,  5.9,  2.3],
       [ 7.7,  3.8,  6.7,  2.2],
       [ 5.1,  3.3,  1.7,  0.5],
       [ 6.7,  3. ,  5. ,  1.7],
       [ 6. ,  3. ,  4.8,  1.8],
       [ 6.1,  2.8,  4.7,  1.2],
       [ 5.8,  4. ,  1.2,  0.2],
       [ 5.8,  2.7,  5.1,  1.9],
       [ 6.3,  2.7,  4.9,  1.8],
       [ 6. ,  2.2,  4. ,  1. ],
       [ 6. ,  2.7,  5.1,  1.6],
       [ 6.4,  2.9,  4.3,  1.3],
       [ 4.4,  3.2,  1.3,  0.2],
       [ 5. ,  2. ,  3.5,  1. ],
       [ 5. ,  3.5,  1.3,  0.3],
       [ 4.8,  3. ,  1.4,  0.3],
       [ 6.3,  2.3,  4.4,  1.3],
       [ 6.7,  3.3,  5.7,  2.1],
       [ 4

In [23]:
knn=KNeighborsClassifier(n_neighbors=8)

In [24]:
knn.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=8, p=2,
           weights='uniform')

In [25]:
y_pred=knn.predict(X_test)

In [26]:
from sklearn.metrics import accuracy_score

In [27]:
accuracy_score(y_test,y_pred)

0.88888888888888884

In [28]:
knn=KNeighborsClassifier(n_neighbors=2)

In [29]:
knn.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=2, p=2,
           weights='uniform')

In [30]:
y_pred=knn.predict(X_test)

In [31]:
accuracy_score(y_test,y_pred)

0.93333333333333335

In [32]:
knn=KNeighborsClassifier(n_neighbors=20)

In [33]:
knn.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=20, p=2,
           weights='uniform')

In [34]:
y_pred=knn.predict(X_test)

In [35]:
accuracy_score(y_test,y_pred)

0.8666666666666667

In [36]:
from sklearn.ensemble import RandomForestClassifier

In [40]:
clf=RandomForestClassifier(n_estimators=130)

In [41]:
clf.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            n_estimators=130, n_jobs=1, oob_score=False, random_state=None,
            verbose=0, warm_start=False)

In [42]:
clf.score(X_test,y_test)

0.93333333333333335

In [43]:
from sklearn.ensemble import AdaBoostClassifier

In [44]:
clf=AdaBoostClassifier()

In [45]:
clf.fit(X_train,y_train)

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None,
          learning_rate=1.0, n_estimators=50, random_state=None)

In [46]:
clf.score(X_test,y_test)

0.93333333333333335