In [105]:
import pandas as pd
import seaborn as sns
import numpy as np
%matplotlib inline

In [131]:
df=pd.read_csv('gapminder1.csv')

In [132]:
df=df.dropna()

In [133]:
X=df.drop('life',axis=1)

In [134]:
y=df['life']

In [135]:
X

Country  Year  fertility  population  child_mortality     gdp  \
0      Afghanistan  1964      7.671  10474903.0            339.7  1182.0   
1      Afghanistan  1965      7.671  10697983.0            334.1  1182.0   
2      Afghanistan  1966      7.671  10927724.0            328.7  1168.0   
3      Afghanistan  1967      7.671  11163656.0            323.3  1173.0   
4      Afghanistan  1968      7.671  11411022.0            318.1  1187.0   
5      Afghanistan  1969      7.671  11676990.0            313.0  1178.0   
6      Afghanistan  1970      7.671  11964906.0            307.8  1174.0   
7      Afghanistan  1971      7.671  12273101.0            302.1  1092.0   
8      Afghanistan  1972      7.671  12593688.0            296.4  1046.0   
9      Afghanistan  1973      7.671  12915499.0            290.8  1137.0   
10     Afghanistan  1974      7.671  13223928.0            284.9  1170.0   
11     Afghanistan  1975      7.671  13505544.0            279.4  1201.0   
12     Afghanistan  1976      7.670  13766792.0            273.6  1231.0   
13     Afghanistan  1977      7.670  14003408.0            267.8  1119.0   
14     Afghanistan  1978      7.670  14179656.0            261.6  1179.0   
15     Afghanistan  1979      7.669  14249493.0            255.5  1155.0   
16     Afghanistan  1980      7.669  14185729.0            249.1  1158.0   
17     Afghanistan  1981      7.670  13984092.0            242.7  1284.0   
18     Afghanistan  1982      7.671  13672870.0            236.2  1402.0   
19     Afghanistan  1983      7.673  13300056.0            229.7  1454.0   
20     Afghanistan  1984      7.676  12931791.0            222.9  1429.0   
21     Afghanistan  1985      7.679  12625292.0            216.0  1384.0   
22     Afghanistan  1986      7.681  12372113.0            209.2  1486.0   
23     Afghanistan  1987      7.682  12183387.0            202.1  1230.0   
24     Afghanistan  1988      7.682  12156685.0            195.0  1113.0   
25     Afghanistan  1989      7.682  12414686.0            187.8  1087.0   
26     Afghanistan  1990      7.687  13032161.0            181.0  1028.0   
27     Afghanistan  1991      7.700  14069854.0            174.2  1022.0   
28     Afghanistan  1992      7.725  15472076.0            167.8   941.0   
29     Afghanistan  1993      7.758  17053213.0            162.0   810.0   
...            ...   ...        ...         ...              ...     ...   
10071     Zimbabwe  1984      6.435   8523090.0             81.5  2327.0   
10072     Zimbabwe  1985      6.223   8855279.0             76.9  2395.0   
10073     Zimbabwe  1986      6.004   9189169.0             72.8  2357.0   
10074     Zimbabwe  1987      5.784   9523376.0             69.8  2299.0   
10075     Zimbabwe  1988      5.569   9852244.0             68.0  2390.0   
10076     Zimbabwe  1989      5.365  10169188.0             67.5  2436.0   
10077     Zimbabwe  1990      5.176  10469202.0             68.3  2532.0   
10078     Zimbabwe  1991      5.001  10748215.0             70.1  2604.0   
10079     Zimbabwe  1992      4.840  11005690.0             72.9  2316.0   
10080     Zimbabwe  1993      4.690  11244552.0             76.0  2292.0   
10081     Zimbabwe  1994      4.554  11469872.0             79.2  2456.0   
10082     Zimbabwe  1995      4.432  11684693.0             82.0  2416.0   
10083     Zimbabwe  1996      4.328  11891290.0             84.2  2619.0   
10084     Zimbabwe  1997      4.240  12086519.0             85.7  2645.0   
10085     Zimbabwe  1998      4.169  12261742.0             86.8  2680.0   
10086     Zimbabwe  1999      4.112  12405236.0             87.8  2625.0   
10087     Zimbabwe  2000      4.069  12509477.0             88.7  2521.0   
10088     Zimbabwe  2001      4.039  12575015.0             89.5  2540.0   
10089     Zimbabwe  2002      4.018  12607791.0             90.6  2304.0   
10090     Zimbabwe  2003      4.002  12612956.0             92.0  1908.0   
10091     Zimbabwe  2004      3.987  12597877.0            

In [136]:
X=X.drop('Country',axis=1)
X=X.drop('region',axis=1)

In [137]:
X

Year  fertility  population  child_mortality     gdp
0      1964      7.671  10474903.0            339.7  1182.0
1      1965      7.671  10697983.0            334.1  1182.0
2      1966      7.671  10927724.0            328.7  1168.0
3      1967      7.671  11163656.0            323.3  1173.0
4      1968      7.671  11411022.0            318.1  1187.0
5      1969      7.671  11676990.0            313.0  1178.0
6      1970      7.671  11964906.0            307.8  1174.0
7      1971      7.671  12273101.0            302.1  1092.0
8      1972      7.671  12593688.0            296.4  1046.0
9      1973      7.671  12915499.0            290.8  1137.0
10     1974      7.671  13223928.0            284.9  1170.0
11     1975      7.671  13505544.0            279.4  1201.0
12     1976      7.670  13766792.0            273.6  1231.0
13     1977      7.670  14003408.0            267.8  1119.0
14     1978      7.670  14179656.0            261.6  1179.0
15     1979      7.669  14249493.0            255.5  1155.0
16     1980      7.669  14185729.0            249.1  1158.0
17     1981      7.670  13984092.0            242.7  1284.0
18     1982      7.671  13672870.0            236.2  1402.0
19     1983      7.673  13300056.0            229.7  1454.0
20     1984      7.676  12931791.0            222.9  1429.0
21     1985      7.679  12625292.0            216.0  1384.0
22     1986      7.681  12372113.0            209.2  1486.0
23     1987      7.682  12183387.0            202.1  1230.0
24     1988      7.682  12156685.0            195.0  1113.0
25     1989      7.682  12414686.0            187.8  1087.0
26     1990      7.687  13032161.0            181.0  1028.0
27     1991      7.700  14069854.0            174.2  1022.0
28     1992      7.725  15472076.0            167.8   941.0
29     1993      7.758  17053213.0            162.0   810.0
...     ...        ...         ...              ...     ...
10071  1984      6.435   8523090.0             81.5  2327.0
10072  1985      6.223   8855279.0             76.9  2395.0
10073  1986      6.004   9189169.0             72.8  2357.0
10074  1987      5.784   9523376.0             69.8  2299.0
10075  1988      5.569   9852244.0             68.0  2390.0
10076  1989      5.365  10169188.0             67.5  2436.0
10077  1990      5.176  10469202.0             68.3  2532.0
10078  1991      5.001  10748215.0             70.1  2604.0
10079  1992      4.840  11005690.0             72.9  2316.0
10080  1993      4.690  11244552.0             76.0  2292.0
10081  1994      4.554  11469872.0             79.2  2456.0
10082  1995      4.432  11684693.0             82.0  2416.0
10083  1996      4.328  11891290.0             84.2  2619.0
10084  1997      4.240  12086519.0             85.7  2645.0
10085  1998      4.169  12261742.0             86.8  2680.0
10086  1999      4.112  12405236.0             87.8  2625.0
10087  2000      4.069  12509477.0             88.7  2521.0
10088  2001      4.039  12575015.0             89.5  2540.0
10089  2002      4.018  12607791.0             90.6  2304.0
10090  2003      4.002  12612956.0             92.0  1908.0
10091  2004      3.987  12597877.0             94.1  1794.0
10092  2005      3.969  12570686.0             96.2  1689.0
10093  2006      3.941  12529655.0             97.9  1629.0
10094  2007      3.903  12481245.0             98.7  1568.0
10095  2008      3.853  12451543.0             98.3  1286.0
10096  2009      3.792  12473992.0             97.3  1352.0
10097  2010      3.721  12571454.0             95.1  1484.0
10098  2011      3.643  12754378.0             92.0  1626.0
10099  2012      3.564  13013678.0             86.7  1750.0
10100  2013      3.486  13327925.0             83.3  1773.0

[8836 rows x 5 columns]

In [138]:
from sklearn.preprocessing import MinMaxScaler

In [139]:
scaler=MinMaxScaler()

In [140]:
X=scaler.fit_transform(X)

In [141]:
X

array([[ 0.        ,  0.89780638,  0.00767885,  0.77846934,  0.00569782],
       [ 0.02040816,  0.89780638,  0.00784296,  0.76556017,  0.00569782],
       [ 0.04081633,  0.89780638,  0.00801197,  0.75311203,  0.00562112],
       ..., 
       [ 0.95918367,  0.36871141,  0.00935576,  0.20746888,  0.00813035],
       [ 0.97959184,  0.35833443,  0.00954651,  0.19525127,  0.0088097 ],
       [ 1.        ,  0.3480888 ,  0.00977769,  0.18741355,  0.00893571]])

In [142]:
from sklearn.model_selection import train_test_split

In [143]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [144]:
len(X_train)

7068

In [145]:
len(X_test)

1768

In [155]:
from sklearn.linear_model import LinearRegression

In [156]:
clf=LinearRegression()

In [157]:
clf.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [158]:
clf.score(X_test,y_test)

0.91274382985440872

In [167]:
y_pred=clf.predict(X_test)

In [168]:
from sklearn.metrics import mean_squared_error
import numpy as np

In [170]:
mean_squared_error(y_test,y_pred)

11.030872828076884

In [159]:
clf.coef_

array([ -1.60856361,  -8.88082643,   1.62791549, -45.3521087 ,  12.72935993])

In [160]:
 from sklearn.linear_model import Ridge

In [161]:
clf=Ridge(alpha=0.1)

In [162]:
clf.fit(X_train,y_train)

Ridge(alpha=0.1, copy_X=True, fit_intercept=True, max_iter=None,
   normalize=False, random_state=None, solver='auto', tol=0.001)

In [163]:
clf.coef_

array([ -1.60413134,  -8.90774996,   1.61800689, -45.29979701,  12.72221362])

In [164]:
X

array([[ 0.        ,  0.89780638,  0.00767885,  0.77846934,  0.00569782],
       [ 0.02040816,  0.89780638,  0.00784296,  0.76556017,  0.00569782],
       [ 0.04081633,  0.89780638,  0.00801197,  0.75311203,  0.00562112],
       ..., 
       [ 0.95918367,  0.36871141,  0.00935576,  0.20746888,  0.00813035],
       [ 0.97959184,  0.35833443,  0.00954651,  0.19525127,  0.0088097 ],
       [ 1.        ,  0.3480888 ,  0.00977769,  0.18741355,  0.00893571]])